# Explore Activity Data 🏃

**Goal of this notebook:** before we design any dashboard screens, we need to see what
data Garmin Connect actually gives us for a run. This notebook:

1. Logs in to Garmin Connect (reusing the cached session token, just like `example.py`).
2. Finds today's activity (e.g. the interval workout you created in the Garmin Connect app).
3. Pulls the raw data for that activity: the summary, the lap/split data, and the
   "typed splits" (which show structured workout steps like warmup / interval / recovery).
4. Searches through that raw data for the running-dynamics fields we care about:
   **pace, cadence, ground contact time (GCT), vertical oscillation**, etc.
5. Saves the raw JSON to `your_data/` so we can refer back to real field names while
   building the dashboard (this folder is git-ignored, so your data never gets committed).

Nothing here builds any UI yet — it's purely "detective work" so the dashboard we build
next is based on real data, not guesses.

## 1. Connect to Garmin

We reuse the same login approach as `example.py`: read `EMAIL` / `PASSWORD` from the
`.env` file, and cache the session token in `~/.garminconnect` so we don't have to log
in every time we run this notebook.

In [1]:
import json
import os
import sys
from datetime import date
from pathlib import Path

# Let this notebook import the local `garminconnect` package no matter where
# Jupyter's working directory happens to be (repo root, notebooks/, etc).
REPO_ROOT = Path.cwd() if (Path.cwd() / "garminconnect").exists() else Path.cwd().parent
sys.path.insert(0, str(REPO_ROOT))

from dotenv import load_dotenv

load_dotenv(REPO_ROOT / ".env")

from garminconnect import (
    Garmin,
    GarminConnectAuthenticationError,
    GarminConnectConnectionError,
    GarminConnectTooManyRequestsError,
)

# Where we'll save raw JSON responses so we can inspect real field names later.
DATA_DIR = REPO_ROOT / "your_data"
DATA_DIR.mkdir(exist_ok=True)

In [2]:
def get_garmin_client() -> Garmin:
    """Log in to Garmin Connect, reusing a cached token if we have one."""
    tokenstore = Path(os.getenv("GARMINTOKENS", "~/.garminconnect")).expanduser()

    try:
        client = Garmin()
        client.login(str(tokenstore))
        print("✅ Logged in using saved tokens.")
        return client
    except GarminConnectTooManyRequestsError as err:
        raise SystemExit(f"Rate limited by Garmin, try again later: {err}") from err
    except (GarminConnectAuthenticationError, GarminConnectConnectionError):
        print("No valid saved tokens — logging in with email/password from .env ...")

    email = os.getenv("EMAIL")
    password = os.getenv("PASSWORD")
    if not email or not password:
        raise SystemExit("Set EMAIL and PASSWORD in your .env file first.")

    client = Garmin(email=email, password=password)
    client.login(str(tokenstore))
    print(f"✅ Login successful. Tokens saved to: {tokenstore}")
    return client


api = get_garmin_client()
print("Logged in as:", api.get_full_name())

✅ Logged in using saved tokens.
Logged in as: Robert Sparks

In [3]:
import pandas as pd


def save_raw(name: str, data: object) -> Path:
    """Save a raw API response as pretty-printed JSON under your_data/, for reference."""
    out_path = DATA_DIR / f"{name}.json"
    out_path.write_text(json.dumps(data, indent=2, default=str))
    print(f"💾 Saved {name} -> {out_path.relative_to(REPO_ROOT)}")
    return out_path


def to_lap_frame(data: object) -> pd.DataFrame:
    """Turn a splits/typed-splits response into a per-lap pandas table.

    Garmin's split endpoints normally return a dict shaped like
    ``{"lapDTOs": [ {...one lap...}, {...next lap...} ]}``. We look for that key
    first, but fall back to scanning for *any* list-of-dicts in the response so
    this keeps working even if Garmin names the field differently for your
    account/activity type.
    """
    if isinstance(data, list):
        return pd.json_normalize(data)

    if isinstance(data, dict):
        if isinstance(data.get("lapDTOs"), list):
            return pd.json_normalize(data["lapDTOs"])
        for value in data.values():
            if isinstance(value, list) and value and isinstance(value[0], dict):
                return pd.json_normalize(value)

    print("⚠️ Could not find a list of laps automatically — inspect the raw JSON above.")
    return pd.DataFrame()


def find_fields(data: object, keywords: list[str], path: str = "") -> list[tuple[str, object]]:
    """Recursively search a nested dict/list for keys containing any of `keywords`.

    Returns a list of (path, example_value) tuples. Useful for hunting down fields
    like "pace", "cadence", "groundContact", "verticalOscillation", etc. without
    knowing the exact key name Garmin uses.
    """
    matches: list[tuple[str, object]] = []
    keywords_lower = [k.lower() for k in keywords]

    if isinstance(data, dict):
        for key, value in data.items():
            new_path = f"{path}.{key}" if path else key
            if any(kw in key.lower() for kw in keywords_lower):
                matches.append((new_path, value))
            matches.extend(find_fields(value, keywords, new_path))
    elif isinstance(data, list):
        for item in data[:1]:  # one example element is enough to see the shape
            matches.extend(find_fields(item, keywords, f"{path}[0]"))

    return matches

## 2. Find today's activity

`get_activities_by_date(start, end)` returns every activity recorded between two dates
(inclusive). We ask for just today, which will include the workout you created in the
Garmin Connect app once it's synced from your watch.

In [ ]:
today = date.today().isoformat()
todays_activities = api.get_activities_by_date(today, today)

print(f"Found {len(todays_activities)} activities today ({today}).\n")

for activity in todays_activities:
    print(
        f"- id={activity['activityId']} | "
        f"'{activity['activityName']}' | "
        f"type={activity['activityType']['typeKey']} | "
        f"start={activity['startTimeLocal']} | "
        f"distance={activity.get('distance', 0) / 1000:.2f} km | "
        f"duration={activity.get('duration', 0) / 60:.1f} min"
    )

if not todays_activities:
    print(
        "No activities found for today yet. If you just finished the workout, "
        "make sure it has synced to Garmin Connect (via the app or a Bluetooth sync), "
        "then re-run this cell."
    )

Found 1 activities today (2026-07-02).

- id=23450669285 | 'County Dublin - intervals' | type=running | start=2026-07-02 08:26:57 | distance=10.88 km | duration=55.5 min

## 3. Pull the full summary for the latest activity

Garmin returns activities newest-first, so `todays_activities[0]` is today's most
recent activity. We fetch its full summary with `get_activity()`, which includes
overall stats (distance, average pace, average cadence, etc. — the whole-run
averages, not per-interval).

If you have more than one activity today, change `ACTIVITY_INDEX` below to pick a
different one (0 = most recent).

In [5]:
ACTIVITY_INDEX = 0  # 0 = today's most recent activity

if not todays_activities:
    raise SystemExit("No activities today yet — nothing to explore.")

activity_id = todays_activities[ACTIVITY_INDEX]["activityId"]
activity_summary = api.get_activity(activity_id)
save_raw("latest_activity_summary", activity_summary)

print(f"Exploring activity {activity_id}: '{activity_summary.get('activityName')}'\n")
print(json.dumps(activity_summary, indent=2, default=str))

💾 Saved latest_activity_summary -> your_data/latest_activity_summary.json
Exploring activity 23450669285: 'County Dublin - intervals'

{
  "activityId": 23450669285,
  "activityUUID": {
    "uuid": "e2008f73-b7a5-46c2-a7a4-a38c49e81a23"
  },
  "activityName": "County Dublin - intervals",
  "userProfileId": 69672142,
  "isMultiSportParent": false,
  "activityTypeDTO": {
    "typeId": 1,
    "typeKey": "running",
    "parentTypeId": 17,
    "isHidden": false,
    "restricted": false,
    "trimmable": true
  },
  "eventTypeDTO": {
    "typeId": 2,
    "typeKey": "recreation",
    "sortOrder": 4
  },
  "accessControlRuleDTO": {
    "typeId": 3,
    "typeKey": "subscribers"
  },
  "timeZoneUnitDTO": {
    "unitId": 159,
    "unitKey": "Europe/London",
    "factor": 0.0,
    "timeZone": "Europe/London"
  },
  "metadataDTO": {
    "isOriginal": true,
    "deviceApplicationInstallationId": 1011746,
    "agentApplicationInstallationId": null,
    "agentString": null,
    "fileFormat": {
      "formatId": 7,
      "formatKey": "fit"
    },
    "associatedCourseId": null,
    "lastUpdateDate": "2026-07-02T19:09:03.0",
    "uploadedDate": "2026-07-02T08:23:43.0",
    "videoUrl": null,
    "hasPolyline": true,
    "hasChartData": true,
    "hasHrTimeInZones": true,
    "hasPowerTimeInZones": true,
    "userInfoDto": {
      "userProfilePk": 69672142,
      "displayname": "2bee7c2a-4448-40c8-9f94-4bf39f2ba68c",
      "fullname": "Robert Sparks",
      "profileImageUrlLarge": "https://s3.amazonaws.com/garmin-connect-prod/profile_images/3af9c8c1-db57-45e3-8e85-64991e20f0c8-prof.png",
      "profileImageUrlMedium": "https://s3.amazonaws.com/garmin-connect-prod/profile_images/3af9c8c1-db57-45e3-8e85-64991e20f0c8-prfr.png",
      "profileImageUrlSmall": "https://s3.amazonaws.com/garmin-connect-prod/profile_images/3af9c8c1-db57-45e3-8e85-64991e20f0c8-prth.png",
      "userPro": false
    },
    "childIds": [],
    "childActivityTypes": [],
    "sensors": null,
    "activityImages": [],
    "manufacturer": "GARMIN",
    "diveNumber": null,
    "lapCount": 16,
    "associatedWorkoutId": 1465118729,
    "isAtpActivity": null,
    "deviceMetaDataDTO": {
      "deviceId": "3617755308",
      "deviceTypePk": 37190,
      "deviceVersionPk": 1011746
    },
    "hasIntensityIntervals": true,
    "hasSplits": true,
    "eBikeMaxAssistModes": null,
    "eBikeBatteryUsage": null,
    "eBikeBatteryRemaining": null,
    "eBikeAssistModeInfoDTOList": null,
    "hasRunPowerWindData": true,
    "calendarEventInfo": null,
    "groupRideUUID": null,
    "hasHeatMap": false,
    "personalRecord": false,
    "runPowerWindDataEnabled": true,
    "elevationCorrected": false,
    "trimmed": false,
    "manualActivity": false,
    "autoCalcCalories": false,
    "favorite": false,
    "gcj02": false
  },
  "summaryDTO": {
    "startTimeLocal": "2026-07-02T08:26:57.0",
    "startTimeGMT": "2026-07-02T07:26:57.0",
    "startLatitude": 53.484583077952266,
    "startLongitude": -6.147782485932112,
    "distance": 10879.02,
    "duration": 3329.407,
    "movingDuration": 3309.819,
    "elapsedDuration": 3334.643,
    "elevationGain": 63.0,
    "elevationLoss": 70.0,
    "maxElevation": 19.6,
    "minElevation": 2.8,
    "avgElevation": 9.81,
    "averageSpeed": 3.2679998874664307,
    "averageMovingSpeed": 3.2868925855001545,
    "maxSpeed": 4.2270002365112305,
    "calories": 774.0,
    "bmrCalories": 80.0,
    "averageHR": 169.0,
    "maxHR": 202.0,
    "minHR": 92.0,
    "averageRunCadence": 175.0,
    "maxRunCadence": 197.0,
    "averagePower": 330.0,
    "maxPower": 537.0,
    "minPower": 0.0,
    "normalizedPower": 359.0,
    "totalWork": 262.52857981584816,
    "groundContactTime": 233.39999389648438,
    "strideLength": 110.85000000000001,
    "verticalOscillation": 8.040000152587892,
    "trainingEffect": 4.5,
    "anaerobicTrainingEffect": 2.4000000953674316,
    "aerobicTrainingEffectMessage": "HIGHLY_IMPROVING_VO2_MAX_16",
    "anaerobicTrainingEffectMessage": "MAINTAINING_ANAEROBIC_BASE_1",
    "verticalRatio": 7.429999828338623,
    "endLatitude": 53.48434176295996,
    "endLongitude": -6.145573602989316,
    "maxVerticalSpeed": 1.7999997138977053,
    "waterEstimated": 895.0,
    "trainingEffectLabel": "VO2MAX",
    "activityTrainingLoad": 261.71441650390625,
    "minActivityLapDuration": 27.384,
    "directWorkoutFeel": 100,
    "directWorkoutRpe": 80,
    "directWorkoutComplianceScore": 84,
    "moderateIntensityMinutes": 5,
    "vigorousIntensityMinutes": 50,
    "steps": 9728,
    "avgGradeAdjustedSpeed": 3.2739999294281006,
    "differenceBodyBattery": -19
  },
  "locationName": "County Dublin",
  "splitSummaries": [
    {
      "distance": 3.85,
      "duration": 12.001,
      "movingDuration": 0.0,
      "elevationGain": 0.0,
      "elevationLoss": 0.0,
      "averageSpeed": 0.32100000977516174,
      "maxSpeed": 0.0,
      "calories": 1.0,
      "bmrCalories": 0.0,
      "averageHR": 105.0,
      "maxHR": 138.0,
      "averageRunCadence": 19.65625,
      "maxRunCadence": 177.0,
      "averagePower": 1.0,
      "maxPower": 14.0,
      "normalizedPower": 50.0,
      "strideLength": 0.0,
      "totalExerciseReps": 0,
      "avgVerticalSpeed": 0.0,
      "avgGradeAdjustedSpeed": 0.0,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "normalizedForce": 0.0,
      "splitType": "RWD_STAND",
      "noOfSplits": 2,
      "maxElevationGain": 0.0,
      "averageElevationGain": 0.0,
      "maxDistance": 3,
      "maxDistanceWithPrecision": 3.85,
      "avgStepFrequency": 19.65625
    },
    {
      "distance": 10473.1,
      "duration": 2989.375,
      "movingDuration": 2984.611,
      "elevationGain": 63.0,
      "elevationLoss": 63.0,
      "averageSpeed": 3.5030000209808354,
      "averageMovingSpeed": 3.5090553437600773,
      "maxSpeed": 4.2270002365112305,
      "calories": 729.0,
      "bmrCalories": 72.0,
      "averageHR": 172.0,
      "maxHR": 202.0,
      "averageRunCadence": 183.546875,
      "maxRunCadence": 197.0,
      "averagePower": 358.0,
      "maxPower": 537.0,
      "normalizedPower": 369.0,
      "groundContactTime": 233.39999389648438,
      "strideLength": 113.68000488281251,
      "verticalOscillation": 8.26999969482422,
      "verticalRatio": 7.360000133514404,
      "totalExerciseReps": 0,
      "avgVerticalSpeed": 0.0,
      "avgGradeAdjustedSpeed": 3.505000114440918,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "normalizedForce": 0.0,
      "splitType": "RWD_RUN",
      "noOfSplits": 5,
      "maxElevationGain": 16.0,
      "averageElevationGain": 13.0,
      "maxDistance": 2247,
      "maxDistanceWithPrecision": 2247.19,
      "avgStepFrequency": 183.546875,
      "avgStepLength": 1.1368000488281251
    },
    {
      "distance": 356.17,
      "duration": 270.0,
      "movingDuration": 259.0,
      "elevationGain": 0.0,
      "elevationLoss": 7.0,
      "averageSpeed": 1.319000005722046,
      "averageMovingSpeed": 1.3750769760508943,
      "maxSpeed": 3.871999979019165,
      "calories": 41.0,
      "bmrCalories": 6.0,
      "averageHR": 149.0,
      "maxHR": 191.0,
      "averageRunCadence": 102.421875,
      "maxRunCadence": 192.0,
      "averagePower": 104.0,
      "maxPower": 452.0,
      "normalizedPower": 254.0,
      "groundContactTime": 239.39999389648438,
      "strideLength": 74.52999877929688,
      "verticalOscillation": 5.95999984741211,
      "verticalRatio": 8.399999618530273,
      "totalExerciseReps": 0,
      "avgVerticalSpeed": 0.0,
      "avgGradeAdjustedSpeed": 1.3739999532699583,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "normalizedForce": 0.0,
      "splitType": "INTERVAL_RECOVERY",
      "noOfSplits": 3,
      "maxElevationGain": 0.0,
      "averageElevationGain": 0.0,
      "maxDistance": 123,
      "maxDistanceWithPrecision": 123.92,
      "avgStepFrequency": 102.421875,
      "avgStepLength": 0.7452999877929688
    },
    {
      "distance": 2429.61,
      "duration": 840.548,
      "movingDuration": 840.0,
      "elevationGain": 10.0,
      "elevationLoss": 10.0,
      "averageSpeed": 2.8910000324249268,
      "averageMovingSpeed": 2.892392985026042,
      "maxSpeed": 4.039999961853027,
      "calories": 182.0,
      "bmrCalories": 20.0,
      "averageHR": 165.0,
      "maxHR": 194.0,
      "averageRunCadence": 169.5625,
      "maxRunCadence": 194.0,
      "averagePower": 278.0,
      "maxPower": 381.0,
      "normalizedPower": 299.0,
      "groundContactTime": 247.0,
      "strideLength": 101.62000122070313,
      "verticalOscillation": 7.990000152587891,
      "verticalRatio": 7.96999979019165,
      "totalExerciseReps": 0,
      "avgVerticalSpeed": 0.0,
      "avgGradeAdjustedSpeed": 2.9149999618530273,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "normalizedForce": 0.0,
      "splitType": "INTERVAL_COOLDOWN",
      "noOfSplits": 1,
      "maxElevationGain": 10.0,
      "averageElevationGain": 10.0,
      "maxDistance": 2429,
      "maxDistanceWithPrecision": 2429.61,
      "avgStepFrequency": 169.5625,
      "avgStepLength": 1.0162000122070314
    },
    {
      "distance": 2093.24,
      "duration": 694.297,
      "movingDuration": 683.0,
      "elevationGain": 14.0,
      "elevationLoss": 16.0,
      "averageSpeed": 3.0150001049041752,
      "averageMovingSpeed": 3.0647730457311493,
      "maxSpeed": 4.2270002365112305,
      "calories": 147.0,
      "bmrCalories": 17.0,
      "averageHR": 151.0,
      "maxHR": 181.0,
      "averageRunCadence": 174.5,
      "maxRunCadence": 195.0,
      "averagePower": 331.0,
      "maxPower": 537.0,
      "normalizedPower": 341.0,
      "groundContactTime": 253.60000610351562,
      "strideLength": 102.94000244140625,
      "verticalOscillation": 8.419999694824218,
      "verticalRatio": 8.220000267028809,
      "totalExerciseReps": 0,
      "avgVerticalSpeed": 0.0,
      "avgGradeAdjustedSpeed": 3.003999948501587,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "normalizedForce": 0.0,
      "splitType": "INTERVAL_WARMUP",
      "noOfSplits": 1,
      "maxElevationGain": 14.0,
      "averageElevationGain": 14.0,
      "maxDistance": 2093,
      "maxDistanceWithPrecision": 2093.24,
      "avgStepFrequency": 174.5,
      "avgStepLength": 1.0294000244140624
    },
    {
      "distance": 402.07,
      "duration": 328.0,
      "movingDuration": 321.0,
      "elevationGain": 0.0,
      "elevationLoss": 7.0,
      "averageSpeed": 1.2259999513626099,
      "averageMovingSpeed": 1.2511325989283377,
      "maxSpeed": 1.5399999618530273,
      "calories": 44.0,
      "bmrCalories": 8.0,
      "averageHR": 146.0,
      "maxHR": 181.0,
      "averageRunCadence": 102.921875,
      "maxRunCadence": 171.0,
      "averagePower": 87.0,
      "maxPower": 124.0,
      "normalizedPower": 159.0,
      "strideLength": 67.54000244140626,
      "verticalOscillation": 5.729999923706055,
      "verticalRatio": 8.550000190734863,
      "totalExerciseReps": 0,
      "avgVerticalSpeed": 0.0,
      "avgGradeAdjustedSpeed": 1.2089999914169312,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "normalizedForce": 0.0,
      "splitType": "RWD_WALK",
      "noOfSplits": 6,
      "maxElevationGain": 0.0,
      "averageElevationGain": 0.0,
      "maxDistance": 141,
      "maxDistanceWithPrecision": 141.7,
      "avgStepFrequency": 102.921875,
      "avgStepLength": 0.6754000244140625
    },
    {
      "distance": 6000.0,
      "duration": 1524.487,
      "movingDuration": 1524.44,
      "elevationGain": 39.0,
      "elevationLoss": 37.0,
      "averageSpeed": 3.936000108718872,
      "averageMovingSpeed": 3.9358718012709257,
      "maxSpeed": 4.179999828338623,
      "calories": 404.0,
      "bmrCalories": 37.0,
      "averageHR": 183.0,
      "maxHR": 202.0,
      "averageRunCadence": 190.9375,
      "maxRunCadence": 197.0,
      "averagePower": 398.0,
      "maxPower": 508.0,
      "normalizedPower": 398.0,
      "groundContactTime": 217.6999969482422,
      "strideLength": 122.54000244140626,
      "verticalOscillation": 8.20999984741211,
      "verticalRatio": 6.699999809265137,
      "totalExerciseReps": 0,
      "avgVerticalSpeed": 0.0010000000474974513,
      "avgGradeAdjustedSpeed": 3.9110000133514404,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "normalizedForce": 0.0,
      "splitType": "INTERVAL_ACTIVE",
      "noOfSplits": 3,
      "maxElevationGain": 16.0,
      "averageElevationGain": 13.0,
      "maxDistance": 2000,
      "maxDistanceWithPrecision": 2000.0,
      "avgStepFrequency": 190.9375,
      "avgStepLength": 1.2254000244140626
    }
  ]
}

## 4. Look at the lap/split data (this is where intervals live)

`get_activity_splits()` returns one entry per lap. For a workout you built in the
Garmin Connect app (warmup / interval / recovery / cooldown), each lap usually
corresponds to one step of that workout — this is how we'll identify "the interval
sections" for the dashboard.

Let's dump the raw JSON first, then load it into a pandas table so it's easier to
scan for useful columns (pace, cadence, GCT, vertical oscillation, heart rate...).

In [6]:
activity_splits = api.get_activity_splits(activity_id)
save_raw("latest_activity_splits", activity_splits)
print(json.dumps(activity_splits, indent=2, default=str))

💾 Saved latest_activity_splits -> your_data/latest_activity_splits.json
{
  "activityId": 23450669285,
  "lapDTOs": [
    {
      "startTimeGMT": "2026-07-02T07:26:57.0",
      "startLatitude": 53.484583077952266,
      "startLongitude": -6.147782485932112,
      "distance": 1000.0,
      "duration": 355.265,
      "movingDuration": 347.0,
      "elapsedDuration": 355.265,
      "elevationGain": 8.0,
      "elevationLoss": 8.0,
      "maxElevation": 19.6,
      "minElevation": 11.8,
      "averageSpeed": 2.815000057220459,
      "averageMovingSpeed": 2.881844380403458,
      "maxSpeed": 3.302999973297119,
      "calories": 70.0,
      "bmrCalories": 9.0,
      "averageHR": 142.0,
      "maxHR": 166.0,
      "averageRunCadence": 170.71875,
      "maxRunCadence": 180.0,
      "averagePower": 306.0,
      "maxPower": 461.0,
      "minPower": 0.0,
      "normalizedPower": 320.0,
      "totalWork": 26.014195636297682,
      "groundContactTime": 260.29998779296875,
      "strideLength": 97.92000122070313,
      "verticalOscillation": 8.35,
      "verticalRatio": 8.529999732971191,
      "endLatitude": 53.48464937880635,
      "endLongitude": -6.157679921016097,
      "maxVerticalSpeed": 0.40000152587890625,
      "avgGradeAdjustedSpeed": 2.8540000915527344,
      "lapIndex": 1,
      "wktStepIndex": 0,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "WARMUP",
      "messageIndex": 0
    },
    {
      "startTimeGMT": "2026-07-02T07:32:53.0",
      "startLatitude": 53.48464191891253,
      "startLongitude": -6.1577213276177645,
      "distance": 1000.0,
      "duration": 311.634,
      "movingDuration": 311.634,
      "elapsedDuration": 311.634,
      "elevationGain": 5.0,
      "elevationLoss": 9.0,
      "maxElevation": 15.0,
      "minElevation": 8.0,
      "averageSpeed": 3.209000110626221,
      "averageMovingSpeed": 3.208892455195418,
      "maxSpeed": 4.189000129699707,
      "calories": 72.0,
      "bmrCalories": 7.0,
      "averageHR": 160.0,
      "maxHR": 181.0,
      "averageRunCadence": 178.0,
      "maxRunCadence": 195.0,
      "averagePower": 353.0,
      "maxPower": 525.0,
      "minPower": 255.0,
      "normalizedPower": 359.0,
      "totalWork": 26.252857981584814,
      "groundContactTime": 247.60000610351562,
      "strideLength": 107.93000488281251,
      "verticalOscillation": 8.51999969482422,
      "verticalRatio": 7.929999828338623,
      "endLatitude": 53.4866311121732,
      "endLongitude": -6.169536793604493,
      "maxVerticalSpeed": 0.4000005722045899,
      "avgGradeAdjustedSpeed": 3.209000110626221,
      "lapIndex": 2,
      "wktStepIndex": 0,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "WARMUP",
      "messageIndex": 1
    },
    {
      "startTimeGMT": "2026-07-02T07:38:05.0",
      "startLatitude": 53.48665399476886,
      "startLongitude": -6.16954056546092,
      "distance": 93.24,
      "duration": 27.384,
      "movingDuration": 26.0,
      "elapsedDuration": 27.384,
      "elevationGain": 1.0,
      "elevationLoss": 0.0,
      "maxElevation": 11.8,
      "minElevation": 11.0,
      "averageSpeed": 3.4049999713897705,
      "averageMovingSpeed": 3.5861537639911356,
      "maxSpeed": 4.2270002365112305,
      "calories": 6.0,
      "bmrCalories": 1.0,
      "averageHR": 155.0,
      "maxHR": 161.0,
      "averageRunCadence": 184.65625,
      "maxRunCadence": 193.0,
      "averagePower": 394.0,
      "maxPower": 537.0,
      "minPower": 314.0,
      "normalizedPower": 345.0,
      "totalWork": 2.386623452871347,
      "groundContactTime": 236.6999969482422,
      "strideLength": 109.80000000000001,
      "verticalOscillation": 8.180000305175781,
      "verticalRatio": 7.46999979019165,
      "endLatitude": 53.48703042604029,
      "endLongitude": -6.170573802664876,
      "maxVerticalSpeed": 0.20000076293945312,
      "avgGradeAdjustedSpeed": 3.4690001010894775,
      "lapIndex": 3,
      "wktStepIndex": 0,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "WARMUP",
      "messageIndex": 2
    },
    {
      "startTimeGMT": "2026-07-02T07:38:31.0",
      "startLatitude": 53.4870471060276,
      "startLongitude": -6.170604228973389,
      "distance": 123.92,
      "duration": 90.0,
      "movingDuration": 90.0,
      "elapsedDuration": 90.0,
      "elevationGain": 0.0,
      "elevationLoss": 1.0,
      "maxElevation": 11.6,
      "minElevation": 9.2,
      "averageSpeed": 1.3769999742507935,
      "averageMovingSpeed": 1.3768888685438367,
      "maxSpeed": 3.013999938964844,
      "calories": 11.0,
      "bmrCalories": 2.0,
      "averageHR": 133.0,
      "maxHR": 153.0,
      "averageRunCadence": 112.46875,
      "maxRunCadence": 173.0,
      "averagePower": 114.0,
      "maxPower": 355.0,
      "minPower": 0.0,
      "normalizedPower": 239.0,
      "totalWork": 2.386623452871347,
      "groundContactTime": 268.0,
      "strideLength": 69.5,
      "verticalOscillation": 5.95,
      "verticalRatio": 8.630000114440918,
      "endLatitude": 53.48768019117415,
      "endLongitude": -6.171951871365309,
      "maxVerticalSpeed": 0.20000076293945312,
      "directWorkoutComplianceScore": 100,
      "avgGradeAdjustedSpeed": 1.4160000085830688,
      "lapIndex": 4,
      "wktStepIndex": 1,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "RECOVERY",
      "messageIndex": 3
    },
    {
      "startTimeGMT": "2026-07-02T07:40:01.0",
      "startLatitude": 53.48768941126764,
      "startLongitude": -6.171995708718896,
      "distance": 1000.0,
      "duration": 254.866,
      "movingDuration": 254.866,
      "elapsedDuration": 254.866,
      "elevationGain": 5.0,
      "elevationLoss": 1.0,
      "maxElevation": 13.8,
      "minElevation": 7.6,
      "averageSpeed": 3.9240000247955322,
      "averageMovingSpeed": 3.9236304981327197,
      "maxSpeed": 4.14300012588501,
      "calories": 65.0,
      "bmrCalories": 6.0,
      "averageHR": 175.0,
      "maxHR": 193.0,
      "averageRunCadence": 191.015625,
      "maxRunCadence": 197.0,
      "averagePower": 381.0,
      "maxPower": 475.0,
      "minPower": 275.0,
      "normalizedPower": 377.0,
      "totalWork": 23.3889098381392,
      "groundContactTime": 218.5,
      "strideLength": 121.7,
      "verticalOscillation": 8.180000305175781,
      "verticalRatio": 6.739999771118164,
      "endLatitude": 53.48827346228063,
      "endLongitude": -6.162527594715357,
      "maxVerticalSpeed": 0.6000003814697266,
      "directWorkoutComplianceScore": 86,
      "avgGradeAdjustedSpeed": 3.9089999198913574,
      "lapIndex": 5,
      "wktStepIndex": 2,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "ACTIVE",
      "messageIndex": 4
    },
    {
      "startTimeGMT": "2026-07-02T07:44:17.0",
      "startLatitude": 53.4882596321404,
      "startLongitude": -6.162477470934391,
      "distance": 1000.0,
      "duration": 253.074,
      "movingDuration": 253.0,
      "elapsedDuration": 253.074,
      "elevationGain": 5.0,
      "elevationLoss": 8.0,
      "maxElevation": 14.6,
      "minElevation": 8.8,
      "averageSpeed": 3.9509999752044678,
      "averageMovingSpeed": 3.952569169960474,
      "maxSpeed": 4.067999839782715,
      "calories": 66.0,
      "bmrCalories": 6.0,
      "averageHR": 184.0,
      "maxHR": 191.0,
      "averageRunCadence": 190.9375,
      "maxRunCadence": 196.0,
      "averagePower": 393.0,
      "maxPower": 461.0,
      "minPower": 345.0,
      "normalizedPower": 391.0,
      "totalWork": 23.627572183426334,
      "groundContactTime": 216.6999969482422,
      "strideLength": 123.8300048828125,
      "verticalOscillation": 8.25,
      "verticalRatio": 6.659999847412109,
      "endLatitude": 53.48376676440239,
      "endLongitude": -6.163389757275581,
      "maxVerticalSpeed": 0.20000076293945312,
      "directWorkoutComplianceScore": 87,
      "avgGradeAdjustedSpeed": 3.934999942779541,
      "lapIndex": 6,
      "wktStepIndex": 2,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "ACTIVE",
      "messageIndex": 5
    },
    {
      "startTimeGMT": "2026-07-02T07:48:30.0",
      "startLatitude": 53.483756789937615,
      "startLongitude": -6.163445916026831,
      "distance": 112.65,
      "duration": 90.0,
      "movingDuration": 83.0,
      "elapsedDuration": 90.0,
      "elevationGain": 0.0,
      "elevationLoss": 5.0,
      "maxElevation": 10.2,
      "minElevation": 5.2,
      "averageSpeed": 1.2519999742507932,
      "averageMovingSpeed": 1.3572289340467338,
      "maxSpeed": 3.871999979019165,
      "calories": 15.0,
      "bmrCalories": 2.0,
      "averageHR": 153.0,
      "maxHR": 182.0,
      "averageRunCadence": 88.625,
      "maxRunCadence": 188.0,
      "averagePower": 100.0,
      "maxPower": 452.0,
      "minPower": 0.0,
      "normalizedPower": 283.0,
      "totalWork": 2.147961107584212,
      "groundContactTime": 232.3000030517578,
      "strideLength": 78.62000122070313,
      "verticalOscillation": 6.05999984741211,
      "verticalRatio": 8.180000305175781,
      "endLatitude": 53.48382803611457,
      "endLongitude": -6.164859104901552,
      "maxVerticalSpeed": 0.40000009536743164,
      "directWorkoutComplianceScore": 100,
      "avgGradeAdjustedSpeed": 1.3179999589920044,
      "lapIndex": 7,
      "wktStepIndex": 1,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "RECOVERY",
      "messageIndex": 6
    },
    {
      "startTimeGMT": "2026-07-02T07:49:59.0",
      "startLatitude": 53.48385343328118,
      "startLongitude": -6.164876036345959,
      "distance": 1000.0,
      "duration": 255.212,
      "movingDuration": 255.212,
      "elapsedDuration": 255.212,
      "elevationGain": 12.0,
      "elevationLoss": 7.0,
      "maxElevation": 11.2,
      "minElevation": 5.0,
      "averageSpeed": 3.9179999828338623,
      "averageMovingSpeed": 3.9183109649928904,
      "maxSpeed": 4.179999828338623,
      "calories": 66.0,
      "bmrCalories": 6.0,
      "averageHR": 179.0,
      "maxHR": 194.0,
      "averageRunCadence": 190.875,
      "maxRunCadence": 195.0,
      "averagePower": 423.0,
      "maxPower": 508.0,
      "minPower": 215.0,
      "normalizedPower": 415.0,
      "totalWork": 25.775533291010547,
      "groundContactTime": 218.89999389648438,
      "strideLength": 121.16999511718751,
      "verticalOscillation": 8.169999694824218,
      "verticalRatio": 6.760000228881836,
      "endLatitude": 53.48940518684685,
      "endLongitude": -6.172351101413369,
      "maxVerticalSpeed": 0.8000001907348633,
      "directWorkoutComplianceScore": 82,
      "avgGradeAdjustedSpeed": 3.868000030517578,
      "lapIndex": 8,
      "wktStepIndex": 2,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "ACTIVE",
      "messageIndex": 7
    },
    {
      "startTimeGMT": "2026-07-02T07:54:15.0",
      "startLatitude": 53.489442402496934,
      "startLongitude": -6.172333583235741,
      "distance": 1000.0,
      "duration": 254.292,
      "movingDuration": 254.292,
      "elapsedDuration": 254.292,
      "elevationGain": 4.0,
      "elevationLoss": 2.0,
      "maxElevation": 13.2,
      "minElevation": 9.2,
      "averageSpeed": 3.931999921798706,
      "averageMovingSpeed": 3.9324869469647705,
      "maxSpeed": 4.086999893188477,
      "calories": 69.0,
      "bmrCalories": 6.0,
      "averageHR": 190.0,
      "maxHR": 196.0,
      "averageRunCadence": 190.46875,
      "maxRunCadence": 196.0,
      "averagePower": 374.0,
      "maxPower": 491.0,
      "minPower": 349.0,
      "normalizedPower": 383.0,
      "totalWork": 22.672922802277796,
      "groundContactTime": 217.5,
      "strideLength": 123.64000244140625,
      "verticalOscillation": 8.26999969482422,
      "verticalRatio": 6.679999828338623,
      "endLatitude": 53.487123381346464,
      "endLongitude": -6.1587193608284,
      "maxVerticalSpeed": 0.20000076293945312,
      "directWorkoutComplianceScore": 83,
      "avgGradeAdjustedSpeed": 3.950000047683716,
      "lapIndex": 9,
      "wktStepIndex": 2,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "ACTIVE",
      "messageIndex": 8
    },
    {
      "startTimeGMT": "2026-07-02T07:58:30.0",
      "startLatitude": 53.48709303885698,
      "startLongitude": -6.158683905377984,
      "distance": 119.6,
      "duration": 90.0,
      "movingDuration": 89.0,
      "elapsedDuration": 90.0,
      "elevationGain": 0.0,
      "elevationLoss": 1.0,
      "maxElevation": 11.2,
      "minElevation": 10.6,
      "averageSpeed": 1.3289999961853027,
      "averageMovingSpeed": 1.3438202075743944,
      "maxSpeed": 3.8440001010894775,
      "calories": 15.0,
      "bmrCalories": 2.0,
      "averageHR": 160.0,
      "maxHR": 191.0,
      "averageRunCadence": 106.078125,
      "maxRunCadence": 192.0,
      "averagePower": 99.0,
      "maxPower": 351.0,
      "minPower": 0.0,
      "normalizedPower": 228.0,
      "totalWork": 2.147961107584212,
      "groundContactTime": 226.8000030517578,
      "strideLength": 82.5,
      "verticalOscillation": 5.879999923706055,
      "verticalRatio": 8.109999656677246,
      "endLatitude": 53.48627052269876,
      "endLongitude": -6.1577357444912195,
      "maxVerticalSpeed": 0.19999980926513672,
      "directWorkoutComplianceScore": 100,
      "avgGradeAdjustedSpeed": 1.3869999647140503,
      "lapIndex": 10,
      "wktStepIndex": 1,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "RECOVERY",
      "messageIndex": 9
    },
    {
      "startTimeGMT": "2026-07-02T07:59:59.0",
      "startLatitude": 53.48624160513282,
      "startLongitude": -6.157709509134293,
      "distance": 1000.0,
      "duration": 254.355,
      "movingDuration": 254.355,
      "elapsedDuration": 254.355,
      "elevationGain": 9.0,
      "elevationLoss": 13.0,
      "maxElevation": 12.2,
      "minElevation": 3.2,
      "averageSpeed": 3.931999921798706,
      "averageMovingSpeed": 3.9315131088330726,
      "maxSpeed": 4.124000072479248,
      "calories": 66.0,
      "bmrCalories": 6.0,
      "averageHR": 179.0,
      "maxHR": 195.0,
      "averageRunCadence": 191.46875,
      "maxRunCadence": 196.0,
      "averagePower": 410.0,
      "maxPower": 464.0,
      "minPower": 327.0,
      "normalizedPower": 403.0,
      "totalWork": 24.820883909862008,
      "groundContactTime": 217.10000610351562,
      "strideLength": 122.3199951171875,
      "verticalOscillation": 8.169999694824218,
      "verticalRatio": 6.679999828338623,
      "endLatitude": 53.486025016754866,
      "endLongitude": -6.16713504306972,
      "maxVerticalSpeed": 1.7999997138977053,
      "directWorkoutComplianceScore": 84,
      "avgGradeAdjustedSpeed": 3.878000020980835,
      "lapIndex": 11,
      "wktStepIndex": 2,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "ACTIVE",
      "messageIndex": 10
    },
    {
      "startTimeGMT": "2026-07-02T08:04:14.0",
      "startLatitude": 53.48604530096054,
      "startLongitude": -6.167183155193925,
      "distance": 1000.0,
      "duration": 252.693,
      "movingDuration": 252.693,
      "elapsedDuration": 257.929,
      "elevationGain": 5.0,
      "elevationLoss": 5.0,
      "maxElevation": 8.0,
      "minElevation": 2.8,
      "averageSpeed": 3.9570000171661377,
      "averageMovingSpeed": 3.957371304517113,
      "maxSpeed": 4.105999946594238,
      "calories": 70.0,
      "bmrCalories": 6.0,
      "averageHR": 192.0,
      "maxHR": 202.0,
      "averageRunCadence": 190.875,
      "maxRunCadence": 195.0,
      "averagePower": 407.0,
      "maxPower": 486.0,
      "minPower": 344.0,
      "normalizedPower": 413.0,
      "totalWork": 24.582221564574873,
      "groundContactTime": 217.8000030517578,
      "strideLength": 122.60999755859376,
      "verticalOscillation": 8.20999984741211,
      "verticalRatio": 6.699999809265137,
      "endLatitude": 53.48936679773033,
      "endLongitude": -6.168477740138769,
      "maxVerticalSpeed": 0.40000009536743164,
      "directWorkoutComplianceScore": 79,
      "avgGradeAdjustedSpeed": 3.9270000457763676,
      "lapIndex": 12,
      "wktStepIndex": 2,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "ACTIVE",
      "messageIndex": 11
    },
    {
      "startTimeGMT": "2026-07-02T08:08:32.0",
      "startLatitude": 53.48935732617974,
      "startLongitude": -6.1684199050068855,
      "distance": 166.31,
      "duration": 123.308,
      "movingDuration": 122.0,
      "elapsedDuration": 123.308,
      "elevationGain": 1.0,
      "elevationLoss": 0.0,
      "maxElevation": 9.2,
      "minElevation": 8.0,
      "averageSpeed": 1.3489999771118162,
      "averageMovingSpeed": 1.3631967012999486,
      "maxSpeed": 4.039999961853027,
      "calories": 19.0,
      "bmrCalories": 3.0,
      "averageHR": 159.0,
      "maxHR": 194.0,
      "averageRunCadence": 121.34375,
      "maxRunCadence": 194.0,
      "averagePower": 115.0,
      "maxPower": 378.0,
      "minPower": 30.0,
      "normalizedPower": 230.0,
      "totalWork": 3.3412728340198856,
      "groundContactTime": 246.8000030517578,
      "strideLength": 70.75,
      "verticalOscillation": 5.8700000762939455,
      "verticalRatio": 8.550000190734863,
      "endLatitude": 53.488901518285275,
      "endLongitude": -6.166151091456413,
      "maxVerticalSpeed": 0.20000076293945312,
      "avgGradeAdjustedSpeed": 1.4589999914169312,
      "lapIndex": 13,
      "wktStepIndex": 4,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "COOLDOWN",
      "messageIndex": 12
    },
    {
      "startTimeGMT": "2026-07-02T08:10:34.0",
      "startLatitude": 53.48889724351466,
      "startLongitude": -6.166121754795313,
      "distance": 1000.0,
      "duration": 313.96,
      "movingDuration": 313.96,
      "elapsedDuration": 313.96,
      "elevationGain": 1.0,
      "elevationLoss": 1.0,
      "maxElevation": 9.2,
      "minElevation": 7.0,
      "averageSpeed": 3.184999942779541,
      "averageMovingSpeed": 3.1851192101433137,
      "maxSpeed": 3.45199990272522,
      "calories": 70.0,
      "bmrCalories": 8.0,
      "averageHR": 163.0,
      "maxHR": 171.0,
      "averageRunCadence": 176.84375,
      "maxRunCadence": 184.0,
      "averagePower": 298.0,
      "maxPower": 349.0,
      "minPower": 0.0,
      "normalizedPower": 297.0,
      "totalWork": 22.43426045699066,
      "groundContactTime": 245.0,
      "strideLength": 106.00999755859375,
      "verticalOscillation": 8.280000305175781,
      "verticalRatio": 7.820000171661377,
      "endLatitude": 53.485753359273076,
      "endLongitude": -6.152819423004985,
      "maxVerticalSpeed": 0.39999961853027344,
      "avgGradeAdjustedSpeed": 3.1640000343322754,
      "lapIndex": 14,
      "wktStepIndex": 4,
      "lengthDTOs": [],
      "wktIndex": 0,
      "connectIQMeasurement": [],
      "intensityType": "COOLDOWN",
      "messageIndex": 13
    },
    {
      "startTimeGMT": "2026-07-02T08:15:49.0",
      "startLatitude": 53.48574413917959,
      "startLongitude": -6.152776507660747,
      "distance": 1000.0,
      "duration": 320.807,
      "movingDuration": 320.807,
      "elapsedDuration": 320.807,
      "elevationGain": 6.0,
      "elevationLoss": 8.0,
      "maxElevation": 13.8,
      "minElevation": 4.6,
      "averageSpeed": 3.117000102996826,
      "averageMovingSpeed": 3.1171388987504427,
      "maxSpeed": 3.378000020980835,
      "calories": 74.0,
      "bmrCalories": 8.0,
      "averageHR": 168.0,
      "maxHR": 180.0,
      "averageRunCadence": 178.375,
      "maxRunCadence": 183.0,

In [7]:
laps_df = to_lap_frame(activity_splits)

# Show only columns that actually have data for at least one lap, so the table
# isn't cluttered with empty/irrelevant fields.
laps_df = laps_df.dropna(axis=1, how="all")
laps_df

,startTimeGMT,startLatitude,startLongitude,distance,duration,movingDuration,elapsedDuration,elevationGain,elevationLoss,maxElevation,...,maxVerticalSpeed,avgGradeAdjustedSpeed,lapIndex,wktStepIndex,lengthDTOs,wktIndex,connectIQMeasurement,intensityType,messageIndex,directWorkoutComplianceScore
0,2026-07-02T07:26:57.0,53.484583,-6.147782,1000.00,355.265,347.000,355.265,8.0,8.0,19.6,...,0.400002,2.854,1,0,[],0,[],WARMUP,0,NaN
1,2026-07-02T07:32:53.0,53.484642,-6.157721,1000.00,311.634,311.634,311.634,5.0,9.0,15.0,...,0.400001,3.209,2,0,[],0,[],WARMUP,1,NaN
2,2026-07-02T07:38:05.0,53.486654,-6.169541,93.24,27.384,26.000,27.384,1.0,0.0,11.8,...,0.200001,3.469,3,0,[],0,[],WARMUP,2,NaN
3,2026-07-02T07:38:31.0,53.487047,-6.170604,123.92,90.000,90.000,90.000,0.0,1.0,11.6,...,0.200001,1.416,4,1,[],0,[],RECOVERY,3,100.0
4,2026-07-02T07:40:01.0,53.487689,-6.171996,1000.00,254.866,254.866,254.866,5.0,1.0,13.8,...,0.600000,3.909,5,2,[],0,[],ACTIVE,4,86.0
5,2026-07-02T07:44:17.0,53.488260,-6.162477,1000.00,253.074,253.000,253.074,5.0,8.0,14.6,...,0.200001,3.935,6,2,[],0,[],ACTIVE,5,87.0
6,2026-07-02T07:48:30.0,53.483757,-6.163446,112.65,90.000,83.000,90.000,0.0,5.0,10.2,...,0.400000,1.318,7,1,[],0,[],RECOVERY,6,100.0
7,2026-07-02T07:49:59.0,53.483853,-6.164876,1000.00,255.212,255.212,255.212,12.0,7.0,11.2,...,0.800000,3.868,8,2,[],0,[],ACTIVE,7,82.0
8,2026-07-02T07:54:15.0,53.489442,-6.172334,1000.00,254.292,254.292,254.292,4.0,2.0,13.2,...,0.200001,3.950,9,2,[],0,[],ACTIVE,8,83.0
9,2026-07-02T07:58:30.0,53.487093,-6.158684,119.60,90.000,89.000,90.000,0.0,1.0,11.2,...,0.200000,1.387,10,1,[],0,[],RECOVERY,9,100.0
10,2026-07-02T07:59:59.0,53.486242,-6.157710,1000.00,254.355,254.355,254.355,9.0,13.0,12.2,...,1.800000,3.878,11,2,[],0,[],ACTIVE,10,84.0
11,2026-07-02T08:04:14.0,53.486045,-6.167183,1000.00,252.693,252.693,257.929,5.0,5.0,8.0,...,0.400000,3.927,12,2,[],0,[],ACTIVE,11,79.0
12,2026-07-02T08:08:32.0,53.489357,-6.168420,166.31,123.308,122.000,123.308,1.0,0.0,9.2,...,0.200001,1.459,13,4,[],0,[],COOLDOWN,12,NaN
13,2026-07-02T08:10:34.0,53.488897,-6.166122,1000.00,313.960,313.960,313.960,1.0,1.0,9.2,...,0.400000,3.164,14,4,[],0,[],COOLDOWN,13,NaN
14,2026-07-02T08:15:49.0,53.485744,-6.152777,1000.00,320.807,320.807,320.807,6.0,8.0,13.8,...,0.400000,3.160,15,4,[],0,[],COOLDOWN,14,NaN
15,2026-07-02T08:21:10.0,53.484687,-6.142624,263.30,82.557,82.000,82.557,1.0,0.0,8.0,...,0.400000,3.162,16,4,[],0,[],COOLDOWN,15,NaN

## 5. Typed splits — structured workout step labels

Because this activity was created as a structured workout, `get_activity_typed_splits()`
should tell us the *type* of each split (e.g. `WARMUP`, `INTERVAL`, `RECOVERY`,
`COOLDOWN`), which is exactly what we need to group laps into "the interval section"
vs "the recovery section" vs "the warmup" on the dashboard.

In [8]:
activity_typed_splits = api.get_activity_typed_splits(activity_id)
save_raw("latest_activity_typed_splits", activity_typed_splits)
print(json.dumps(activity_typed_splits, indent=2, default=str))

💾 Saved latest_activity_typed_splits -> your_data/latest_activity_typed_splits.json
{
  "activityId": 23450669285,
  "activityUUID": {
    "uuid": "e2008f73-b7a5-46c2-a7a4-a38c49e81a23"
  },
  "splits": [
    {
      "startTimeLocal": "2026-07-02T08:26:57.0",
      "startTimeGMT": "2026-07-02T07:26:57.0",
      "distance": 0.0,
      "duration": 9.001,
      "movingDuration": 0.0,
      "elapsedDuration": 9.001,
      "elevationGain": 0.0,
      "elevationLoss": 0.0,
      "averageSpeed": 0.0,
      "maxSpeed": 0.0,
      "calories": 1.0,
      "bmrCalories": 0.0,
      "averageHR": 94.0,
      "maxHR": 95.0,
      "averageRunCadence": 19.65625,
      "maxRunCadence": 177.0,
      "averagePower": 2.0,
      "maxPower": 14.0,
      "strideLength": 0.0,
      "totalExerciseReps": 0,
      "endLatitude": 53.484583077952266,
      "endLongitude": -6.147782485932112,
      "avgVerticalSpeed": 0.0,
      "avgGradeAdjustedSpeed": 0.0,
      "avgElapsedDurationVerticalSpeed": 0.02857140132359096,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "RWD_STAND",
      "messageIndex": 0,
      "endTimeGMT": "2026-07-02T07:27:05.0",
      "startElevation": 29.6
    },
    {
      "startTimeLocal": "2026-07-02T08:26:57.0",
      "startTimeGMT": "2026-07-02T07:26:57.0",
      "startLatitude": 53.484583077952266,
      "startLongitude": -6.147782485932112,
      "distance": 2093.24,
      "duration": 694.297,
      "movingDuration": 683.0,
      "elapsedDuration": 694.297,
      "elevationGain": 14.0,
      "elevationLoss": 16.0,
      "averageSpeed": 3.0150001049041752,
      "averageMovingSpeed": 3.0647730457311493,
      "maxSpeed": 4.2270002365112305,
      "calories": 147.0,
      "bmrCalories": 17.0,
      "averageHR": 151.0,
      "maxHR": 181.0,
      "averageRunCadence": 174.5,
      "maxRunCadence": 195.0,
      "averagePower": 331.0,
      "maxPower": 537.0,
      "normalizedPower": 341.0,
      "groundContactTime": 253.60000610351562,
      "strideLength": 102.94000244140625,
      "verticalOscillation": 8.419999694824218,
      "verticalRatio": 8.220000267028809,
      "totalExerciseReps": 0,
      "endLatitude": 53.48703042604029,
      "endLongitude": -6.170573802664876,
      "avgVerticalSpeed": -0.004000000189989805,
      "avgGradeAdjustedSpeed": 3.003999948501587,
      "avgElapsedDurationVerticalSpeed": -0.0020231208360264067,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "INTERVAL_WARMUP",
      "messageIndex": 1,
      "lapIndexes": [
        1,
        2,
        3
      ],
      "endTimeGMT": "2026-07-02T07:38:30.0",
      "startElevation": 29.6,
      "avgStepLength": 1.0294000244140624
    },
    {
      "startTimeLocal": "2026-07-02T08:27:06.0",
      "startTimeGMT": "2026-07-02T07:27:06.0",
      "startLatitude": 53.4845604468137,
      "startLongitude": -6.147795142605901,
      "distance": 2115.1,
      "duration": 699.0,
      "movingDuration": 697.0,
      "elapsedDuration": 699.0,
      "elevationGain": 14.0,
      "elevationLoss": 16.0,
      "averageSpeed": 3.0260000228881836,
      "averageMovingSpeed": 3.0345768976416787,
      "maxSpeed": 4.2270002365112305,
      "calories": 149.0,
      "bmrCalories": 17.0,
      "averageHR": 151.0,
      "maxHR": 181.0,
      "averageRunCadence": 174.75,
      "maxRunCadence": 195.0,
      "averagePower": 331.0,
      "maxPower": 537.0,
      "normalizedPower": 341.0,
      "groundContactTime": 253.60000610351562,
      "strideLength": 102.75999755859375,
      "verticalOscillation": 8.40999984741211,
      "verticalRatio": 8.220000267028809,
      "totalExerciseReps": 0,
      "endLatitude": 53.48719898611307,
      "endLongitude": -6.170735992491245,
      "avgVerticalSpeed": -0.004000000189989805,
      "avgGradeAdjustedSpeed": 3.0260000228881836,
      "avgElapsedDurationVerticalSpeed": -0.0028653295128939823,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "RWD_RUN",
      "messageIndex": 2,
      "endTimeGMT": "2026-07-02T07:38:44.0",
      "startElevation": 30.0,
      "avgStepLength": 1.0275999755859375
    },
    {
      "startTimeLocal": "2026-07-02T08:38:31.0",
      "startTimeGMT": "2026-07-02T07:38:31.0",
      "startLatitude": 53.4870471060276,
      "startLongitude": -6.170604228973389,
      "distance": 123.92,
      "duration": 90.0,
      "movingDuration": 89.0,
      "elapsedDuration": 90.0,
      "elevationGain": 0.0,
      "elevationLoss": 1.0,
      "averageSpeed": 1.3769999742507935,
      "averageMovingSpeed": 1.3923595299881493,
      "maxSpeed": 3.013999938964844,
      "calories": 11.0,
      "bmrCalories": 2.0,
      "averageHR": 133.0,
      "maxHR": 153.0,
      "averageRunCadence": 112.453125,
      "maxRunCadence": 173.0,
      "averagePower": 114.0,
      "maxPower": 355.0,
      "normalizedPower": 239.0,
      "groundContactTime": 268.0,
      "strideLength": 69.5,
      "verticalOscillation": 5.95,
      "verticalRatio": 8.630000114440918,
      "totalExerciseReps": 0,
      "endLatitude": 53.48768019117415,
      "endLongitude": -6.171951871365309,
      "avgVerticalSpeed": -0.01600000075995922,
      "avgGradeAdjustedSpeed": 1.4160000085830688,
      "avgElapsedDurationVerticalSpeed": -0.02247191011235955,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "INTERVAL_RECOVERY",
      "messageIndex": 3,
      "lapIndexes": [
        4
      ],
      "endTimeGMT": "2026-07-02T07:40:00.0",
      "startElevation": 11.4,
      "avgStepLength": 0.695
    },
    {
      "startTimeLocal": "2026-07-02T08:38:45.0",
      "startTimeGMT": "2026-07-02T07:38:45.0",
      "startLatitude": 53.487210385501385,
      "startLongitude": -6.17074160836637,
      "distance": 98.94,
      "duration": 75.0,
      "movingDuration": 74.0,
      "elapsedDuration": 75.0,
      "elevationGain": 0.0,
      "elevationLoss": 1.0,
      "averageSpeed": 1.319000005722046,
      "averageMovingSpeed": 1.3370270600190033,
      "maxSpeed": 1.4459999799728391,
      "calories": 8.0,
      "bmrCalories": 2.0,
      "averageHR": 130.0,
      "maxHR": 153.0,
      "averageRunCadence": 116.34375,
      "maxRunCadence": 171.0,
      "averagePower": 107.0,
      "maxPower": 124.0,
      "normalizedPower": 156.0,
      "strideLength": 67.49000244140625,
      "verticalOscillation": 5.779999923706055,
      "verticalRatio": 8.569999694824219,
      "totalExerciseReps": 0,
      "endLatitude": 53.487670216709375,
      "endLongitude": -6.17190795019269,
      "avgVerticalSpeed": -0.019999999552965164,
      "avgGradeAdjustedSpeed": 1.2680000066757202,
      "avgElapsedDurationVerticalSpeed": -0.02432431401433172,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "RWD_WALK",
      "messageIndex": 4,
      "endTimeGMT": "2026-07-02T07:39:59.0",
      "startElevation": 11.4,
      "avgStepLength": 0.6749000244140625
    },
    {
      "startTimeLocal": "2026-07-02T08:40:00.0",
      "startTimeGMT": "2026-07-02T07:40:00.0",
      "startLatitude": 53.48768019117415,
      "startLongitude": -6.171951871365309,
      "distance": 2031.67,
      "duration": 524.0,
      "movingDuration": 523.0,
      "elapsedDuration": 524.0,
      "elevationGain": 9.0,
      "elevationLoss": 9.0,
      "averageSpeed": 3.8770000934600835,
      "averageMovingSpeed": 3.8846463555359705,
      "maxSpeed": 4.14300012588501,
      "calories": 135.0,
      "bmrCalories": 13.0,
      "averageHR": 180.0,
      "maxHR": 193.0,
      "averageRunCadence": 188.984375,
      "maxRunCadence": 197.0,
      "averagePower": 383.0,
      "maxPower": 475.0,
      "normalizedPower": 385.0,
      "groundContactTime": 218.0,
      "strideLength": 122.3199951171875,
      "verticalOscillation": 8.200000000000001,
      "verticalRatio": 6.71999979019165,
      "totalExerciseReps": 0,
      "endLatitude": 53.48368923179805,
      "endLongitude": -6.163780353963375,
      "avgVerticalSpeed": 0.0010000000474974513,
      "avgGradeAdjustedSpeed": 3.8829998970031743,
      "avgElapsedDurationVerticalSpeed": 0.0011472282628484255,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "RWD_RUN",
      "messageIndex": 5,
      "endTimeGMT": "2026-07-02T07:48:43.0",
      "startElevation": 9.4,
      "avgStepLength": 1.223199951171875
    },
    {
      "startTimeLocal": "2026-07-02T08:40:01.0",
      "startTimeGMT": "2026-07-02T07:40:01.0",
      "startLatitude": 53.48768941126764,
      "startLongitude": -6.171995708718896,
      "distance": 2000.0,
      "duration": 507.938,
      "movingDuration": 507.938,
      "elapsedDuration": 507.938,
      "elevationGain": 9.0,
      "elevationLoss": 9.0,
      "averageSpeed": 3.937000036239624,
      "averageMovingSpeed": 3.937488524470395,
      "maxSpeed": 4.14300012588501,
      "calories": 132.0,
      "bmrCalories": 12.0,
      "averageHR": 180.0,
      "maxHR": 193.0,
      "averageRunCadence": 190.96875,
      "maxRunCadence": 197.0,
      "averagePower": 387.0,
      "maxPower": 475.0,
      "normalizedPower": 384.0,
      "groundContactTime": 217.60000610351562,
      "strideLength": 122.75999755859375,
      "verticalOscillation": 8.20999984741211,
      "verticalRatio": 6.699999809265137,
      "totalExerciseReps": 0,
      "endLatitude": 53.48376676440239,
      "endLongitude": -6.163389757275581,
      "avgVerticalSpeed": 0.0010000000474974513,
      "avgGradeAdjustedSpeed": 3.921999931335449,
      "avgElapsedDurationVerticalSpeed": 0.001968503937007874,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "INTERVAL_ACTIVE",
      "messageIndex": 6,
      "lapIndexes": [
        5,
        6
      ],
      "endTimeGMT": "2026-07-02T07:48:29.0",
      "startElevation": 9.2,
      "avgStepLength": 1.2275999755859375
    },
    {
      "startTimeLocal": "2026-07-02T08:48:30.0",
      "startTimeGMT": "2026-07-02T07:48:30.0",
      "startLatitude": 53.483756789937615,
      "startLongitude": -6.163445916026831,
      "distance": 112.65,
      "duration": 90.0,
      "movingDuration": 82.0,
      "elapsedDuration": 89.997,
      "elevationGain": 0.0,
      "elevationLoss": 5.0,
      "averageSpeed": 1.2519999742507932,
      "averageMovingSpeed": 1.3737805064131574,
      "maxSpeed": 3.871999979019165,
      "calories": 15.0,
      "bmrCalories": 2.0,
      "averageHR": 153.0,
      "maxHR": 182.0,
      "averageRunCadence": 88.609375,
      "maxRunCadence": 188.0,
      "averagePower": 100.0,
      "maxPower": 452.0,
      "normalizedPower": 283.0,
      "groundContactTime": 232.3000030517578,
      "strideLength": 78.62000122070313,
      "verticalOscillation": 6.05999984741211,
      "verticalRatio": 8.180000305175781,
      "totalExerciseReps": 0,
      "endLatitude": 53.48382803611457,
      "endLongitude": -6.164859104901552,
      "avgVerticalSpeed": -0.052000001072883606,
      "avgGradeAdjustedSpeed": 1.3179999589920044,
      "avgElapsedDurationVerticalSpeed": -0.04545454003594138,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "INTERVAL_RECOVERY",
      "messageIndex": 7,
      "lapIndexes": [
        7
      ],
      "endTimeGMT": "2026-07-02T07:49:58.0",
      "startElevation": 10.2,
      "avgStepLength": 0.7862000122070313
    },
    {
      "startTimeLocal": "2026-07-02T08:48:44.0",
      "startTimeGMT": "2026-07-02T07:48:44.0",
      "startLatitude": 53.48368277773261,
      "startLongitude": -6.163794351741672,
      "distance": 44.14,
      "duration": 48.0,
      "movingDuration": 45.0,
      "elapsedDuration": 48.0,
      "elevationGain": 0.0,
      "elevationLoss": 2.0,
      "averageSpeed": 0.9200000166893005,
      "averageMovingSpeed": 0.9808888753255208,
      "maxSpeed": 1.4739999771118164,
      "calories": 9.0,
      "bmrCalories": 1.0,
      "averageHR": 156.0,
      "maxHR": 175.0,
      "averageRunCadence": 83.90625,
      "maxRunCadence": 120.0,
      "averagePower": 73.0,
      "maxPower": 120.0,
      "normalizedPower": 212.0,
      "strideLength": 67.2,
      "verticalOscillation": 5.740000152587891,
      "verticalRatio": 8.600000381469727,
      "totalExerciseReps": 0,
      "endLatitude": 53.483632151037455,
      "endLongitude": -6.164406817406416,
      "avgVerticalSpeed": -0.04500000178813934,
      "avgGradeAdjustedSpeed": 1.1069999933242798,
      "avgElapsedDurationVerticalSpeed": -0.06382978723404255,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "RWD_WALK",
      "messageIndex": 8,
      "endTimeGMT": "2026-07-02T07:49:31.0",
      "startElevation": 10.0,
      "avgStepLength": 0.672
    },
    {
      "startTimeLocal": "2026-07-02T08:49:32.0",
      "startTimeGMT": "2026-07-02T07:49:32.0",
      "startLatitude": 53.48363374359906,
      "startLongitude": -6.164427939802408,
      "distance": 3.85,
      "duration": 3.0,
      "movingDuration": 0.0,
      "elapsedDuration": 3.0,
      "elevationGain": 0.0,
      "elevationLoss": 0.0,
      "averageSpeed": 1.2829999923706055,
      "maxSpeed": 0.0,
      "calories": 0.0,
      "bmrCalories": 0.0,
      "averageHR": 137.0,
      "maxHR": 138.0,
      "averageRunCadence": 0.0,
      "maxRunCadence": 0.0,
      "averagePower": 0.0,
      "maxPower": 0.0,
      "normalizedPower": 50.0,
      "totalExerciseReps": 0,
      "endLatitude": 53.483638102188706,
      "endLongitude": -6.164464568719268,
      "avgVerticalSpeed": 0.0,
      "avgGradeAdjustedSpeed": 0.0,
      "avgElapsedDurationVerticalSpeed": -0.09999990463256836,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "RWD_STAND",
      "messageIndex": 9,
      "endTimeGMT": "2026-07-02T07:49:34.0",
      "startElevation": 6.8
    },
    {
      "startTimeLocal": "2026-07-02T08:49:35.0",
      "startTimeGMT": "2026-07-02T07:49:35.0",
      "startLatitude": 53.483642879873514,
      "startLongitude": -6.164475046098232,
      "distance": 36.11,
      "duration": 24.0,
      "movingDuration": 23.0,
      "elapsedDuration": 24.0,
      "elevationGain": 0.0,
      "elevationLoss": 3.0,
      "averageSpeed": 1.5049999952316284,
      "averageMovingSpeed": 1.5700000265370244,
      "maxSpeed": 1.4179999828338623,
      "calories": 2.0,
      "bmrCalories": 1.0,
      "averageHR": 133.0,
      "maxHR": 137.0,
      "averageRunCadence": 92.078125,
      "maxRunCadence": 111.0,
      "averagePower": 79.0,
      "maxPower": 114.0,
      "normalizedPower": 45.0,
      "strideLength": 71.35000000000001,
      "verticalOscillation": 5.75999984741211,
      "verticalRatio": 8.119999885559082,
      "totalExerciseReps": 0,
      "endLatitude": 53.48382803611457,
      "endLongitude": -6.164859104901552,
      "avgVerticalSpeed": -0.10499999672174454,
      "avgGradeAdjustedSpeed": 1.11899995803833,
      "avgElapsedDurationVerticalSpeed": -0.008695643881092901,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "RWD_WALK",
      "messageIndex": 10,
      "endTimeGMT": "2026-07-02T07:49:58.0",
      "startElevation": 6.6,
      "avgStepLength": 0.7135000000000001
    },
    {
      "startTimeLocal": "2026-07-02T08:49:59.0",
      "startTimeGMT": "2026-07-02T07:49:59.0",
      "startLatitude": 53.48385343328118,
      "startLongitude": -6.164876036345959,
      "distance": 2035.22,
      "duration": 526.0,
      "movingDuration": 525.0,
      "elapsedDuration": 526.0,
      "elevationGain": 16.0,
      "elevationLoss": 10.0,
      "averageSpeed": 3.8689999580383305,
      "averageMovingSpeed": 3.8766094680059524,
      "maxSpeed": 4.179999828338623,
      "calories": 139.0,
      "bmrCalories": 13.0,
      "averageHR": 185.0,
      "maxHR": 196.0,
      "averageRunCadence": 188.828125,
      "maxRunCadence": 196.0,
      "averagePower": 393.0,
      "maxPower": 508.0,
      "normalizedPower": 399.0,
      "groundContactTime": 218.1999969482422,
      "strideLength": 122.35999755859376,
      "verticalOscillation": 8.200000000000001,
      "verticalRatio": 6.71999979019165,
      "totalExerciseReps": 0,
      "endLatitude": 53.48687930032611,
      "endLongitude": -6.158466478809714,
      "avgVerticalSpeed": 0.01200000010430813,
      "avgGradeAdjustedSpeed": 3.874000072479248,
      "avgElapsedDurationVerticalSpeed": 0.008761904580252512,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "RWD_RUN",
      "messageIndex": 11,
      "endTimeGMT": "2026-07-02T07:58:44.0",
      "startElevation": 6.8,
      "avgStepLength": 1.2235999755859377
    },
    {
      "startTimeLocal": "2026-07-02T08:49:59.0",
      "startTimeGMT": "2026-07-02T07:49:59.0",
      "startLatitude": 53.48385343328118,
      "startLongitude": -6.164876036345959,
      "distance": 2000.0,
      "duration": 509.502,
      "movingDuration": 509.502,
      "elapsedDuration": 509.502,
      "elevationGain": 16.0,
      "elevationLoss": 10.0,
      "averageSpeed": 3.924999952316284,
      "averageMovingSpeed": 3.925401557630197,
      "maxSpeed": 4.179999828338623,
      "calories": 136.0,
      "bmrCalories": 12.0,
      "averageHR": 185.0,
      "maxHR": 196.0,
      "averageRunCadence": 190.65625,
      "maxRunCadence": 196.0,
      "averagePower": 398.0,
      "maxPower": 508.0,
      "normalizedPower": 400.0,
      "groundContactTime": 218.1999969482422,
      "strideLength": 122.4,
      "verticalOscillation": 8.219999694824219,
      "verticalRatio": 6.71999979019165,
      "totalExerciseReps": 0,
      "endLatitude": 53.487123381346464,
      "endLongitude": -6.1587193608284,
      "avgVerticalSpeed": 0.01200000010430813,
      "avgGradeAdjustedSpeed": 3.9089999198913574,
      "avgElapsedDurationVerticalSpeed": 0.009411764144897462,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "INTERVAL_ACTIVE",
      "messageIndex": 12,
      "lapIndexes": [
        8,
        9
      ],
      "endTimeGMT": "2026-07-02T07:58:29.0",
      "startElevation": 6.8,
      "avgStepLength": 1.224
    },
    {
      "startTimeLocal": "2026-07-02T08:58:30.0",
      "startTimeGMT": "2026-07-02T07:58:30.0",
      "startLatitude": 53.48709303885698,
      "startLongitude": -6.158683905377984,
      "distance": 119.6,
      "duration": 90.0,
      "movingDuration": 88.0,
      "elapsedDuration": 90.0,
      "elevationGain": 0.0,
      "elevationLoss": 1.0,
      "averageSpeed": 1.3289999961853027,
      "averageMovingSpeed": 1.359090891751376,
      "maxSpeed": 3.8440001010894775,
      "calories": 15.0,
      "bmrCalories": 2.0,
      "averageHR": 160.0,
      "maxHR": 191.0,
      "averageRunCadence": 106.078125,
      "maxRunCadence": 192.0,
      "averagePower": 99.0,
      "maxPower": 351.0,
      "normalizedPower": 228.0,
      "groundContactTime": 226.8000030517578,
      "strideLength": 82.5,
      "verticalOscillation": 5.879999923706055,
      "verticalRatio": 8.109999656677246,
      "totalExerciseReps": 0,
      "endLatitude": 53.48627052269876,
      "endLongitude": -6.1577357444912195,
      "avgVerticalSpeed": -0.01200000010430813,
      "avgGradeAdjustedSpeed": 1.3869999647140503,
      "avgElapsedDurationVerticalSpeed": -0.004545450210571289,
      "avgForce": 0.0,
      "maxForce": 0.0,
      "type": "INTERVAL_RECOVERY",
      "messageIndex": 13,
      "lapIndexes": [
        10
      ],
      "endTimeGMT": "2026-07-02T07:59:58.0",
      "startElevation": 11.2,
      "avgStepLength": 0.825
    },
    {
      "startTimeLocal": "2026-07-02T08:58:45.0",
      "startTimeGMT": "2026-07-02T07:58:45.0",
      "startLatitude": 53.48687058314681,
      "startLongitude": -6.158453989773989,
      "distance": 81.18,
      "duration": 73.0,
      "movingDuration": 72.0,
      "elapsedDuration": 73.0,
      "elevationGain": 0.0,
      "elevationLoss": 1.0,
      "averageSpeed": 1.1119999885559082,
      "averageMovingSpeed": 1.1275000042385526,
      "maxSpeed": 1.2970000505447388,
      "calories": 11.0,
      "bmrCalories": 2.0,
      "averageHR": 155.0,
      "maxHR": 181.0,
      "averageRunCadence": 100.8125,
      "maxRunCadence": 125.0,
      "averagePower": 77.0,
      "maxPower": 99.0,
      "normalizedPower": 149.0,

In [9]:
typed_laps_df = to_lap_frame(activity_typed_splits)
typed_laps_df = typed_laps_df.dropna(axis=1, how="all")
typed_laps_df

,startTimeLocal,startTimeGMT,distance,duration,movingDuration,elapsedDuration,elevationGain,elevationLoss,averageSpeed,maxSpeed,...,startElevation,startLatitude,startLongitude,averageMovingSpeed,normalizedPower,groundContactTime,verticalOscillation,verticalRatio,lapIndexes,avgStepLength
0,2026-07-02T08:26:57.0,2026-07-02T07:26:57.0,0.00,9.001,0.000,9.001,0.0,0.0,0.000,0.000,...,29.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-02T08:26:57.0,2026-07-02T07:26:57.0,2093.24,694.297,683.000,694.297,14.0,16.0,3.015,4.227,...,29.6,53.484583,-6.147782,3.064773,341.0,253.600006,8.42,8.22,"[1, 2, 3]",1.0294
2,2026-07-02T08:27:06.0,2026-07-02T07:27:06.0,2115.10,699.000,697.000,699.000,14.0,16.0,3.026,4.227,...,30.0,53.484560,-6.147795,3.034577,341.0,253.600006,8.41,8.22,NaN,1.0276
3,2026-07-02T08:38:31.0,2026-07-02T07:38:31.0,123.92,90.000,89.000,90.000,0.0,1.0,1.377,3.014,...,11.4,53.487047,-6.170604,1.392360,239.0,268.000000,5.95,8.63,[4],0.6950
4,2026-07-02T08:38:45.0,2026-07-02T07:38:45.0,98.94,75.000,74.000,75.000,0.0,1.0,1.319,1.446,...,11.4,53.487210,-6.170742,1.337027,156.0,NaN,5.78,8.57,NaN,0.6749
5,2026-07-02T08:40:00.0,2026-07-02T07:40:00.0,2031.67,524.000,523.000,524.000,9.0,9.0,3.877,4.143,...,9.4,53.487680,-6.171952,3.884646,385.0,218.000000,8.20,6.72,NaN,1.2232
6,2026-07-02T08:40:01.0,2026-07-02T07:40:01.0,2000.00,507.938,507.938,507.938,9.0,9.0,3.937,4.143,...,9.2,53.487689,-6.171996,3.937489,384.0,217.600006,8.21,6.70,"[5, 6]",1.2276
7,2026-07-02T08:48:30.0,2026-07-02T07:48:30.0,112.65,90.000,82.000,89.997,0.0,5.0,1.252,3.872,...,10.2,53.483757,-6.163446,1.373781,283.0,232.300003,6.06,8.18,[7],0.7862
8,2026-07-02T08:48:44.0,2026-07-02T07:48:44.0,44.14,48.000,45.000,48.000,0.0,2.0,0.920,1.474,...,10.0,53.483683,-6.163794,0.980889,212.0,NaN,5.74,8.60,NaN,0.6720
9,2026-07-02T08:49:32.0,2026-07-02T07:49:32.0,3.85,3.000,0.000,3.000,0.0,0.0,1.283,0.000,...,6.8,53.483634,-6.164428,NaN,50.0,NaN,NaN,NaN,NaN,NaN
10,2026-07-02T08:49:35.0,2026-07-02T07:49:35.0,36.11,24.000,23.000,24.000,0.0,3.0,1.505,1.418,...,6.6,53.483643,-6.164475,1.570000,45.0,NaN,5.76,8.12,NaN,0.7135
11,2026-07-02T08:49:59.0,2026-07-02T07:49:59.0,2035.22,526.000,525.000,526.000,16.0,10.0,3.869,4.180,...,6.8,53.483853,-6.164876,3.876609,399.0,218.199997,8.20,6.72,NaN,1.2236
12,2026-07-02T08:49:59.0,2026-07-02T07:49:59.0,2000.00,509.502,509.502,509.502,16.0,10.0,3.925,4.180,...,6.8,53.483853,-6.164876,3.925402,400.0,218.199997,8.22,6.72,"[8, 9]",1.2240
13,2026-07-02T08:58:30.0,2026-07-02T07:58:30.0,119.60,90.000,88.000,90.000,0.0,1.0,1.329,3.844,...,11.2,53.487093,-6.158684,1.359091,228.0,226.800003,5.88,8.11,[10],0.8250
14,2026-07-02T08:58:45.0,2026-07-02T07:58:45.0,81.18,73.000,72.000,73.000,0.0,1.0,1.112,1.297,...,11.2,53.486871,-6.158454,1.127500,149.0,NaN,5.65,8.72,NaN,0.6607
15,2026-07-02T08:59:58.0,2026-07-02T07:59:58.0,2043.92,529.764,529.000,535.000,15.0,19.0,3.858,4.124,...,11.0,53.486271,-6.157736,3.863743,406.0,218.399994,8.11,6.73,NaN,1.2170
16,2026-07-02T08:59:59.0,2026-07-02T07:59:59.0,2000.00,507.047,507.000,512.283,14.0,19.0,3.944,4.124,...,11.0,53.486242,-6.157710,3.944773,408.0,217.399994,8.19,6.69,"[11, 12]",1.2247
17,2026-07-02T09:08:32.0,2026-07-02T08:08:32.0,2429.61,840.548,840.000,887.194,10.0,10.0,2.891,4.040,...,8.0,53.489357,-6.168420,2.892393,299.0,247.000000,7.99,7.97,"[13, 14, 15, 16]",1.0162
18,2026-07-02T09:08:53.0,2026-07-02T08:08:53.0,141.70,108.000,107.000,108.000,0.0,0.0,1.312,1.540,...,8.6,53.489233,-6.167920,1.324299,133.0,NaN,5.76,8.55,NaN,0.6741
19,2026-07-02T09:10:41.0,2026-07-02T08:10:41.0,2247.19,710.611,710.611,727.000,9.0,10.0,3.162,3.452,...,8.6,53.488850,-6.165883,3.162335,308.0,247.000000,8.35,7.90,NaN,1.0579

## 6. Hunt for the running-dynamics fields we actually care about

Rather than guessing exact Garmin field names, let's search everything we've pulled so
far for keys that look related to **pace, cadence, ground contact time (GCT),
vertical oscillation, stride length**, and **heart rate**. This tells us exactly which
field to use for each stat on the dashboard.

In [10]:
KEYWORDS = [
    "pace",
    "speed",
    "cadence",
    "groundcontact",
    "ground_contact",
    "verticaloscillation",
    "verticalratio",
    "stride",
    "heartrate",
    "hr",
]

all_sources = {
    "activity_summary": activity_summary,
    "activity_splits": activity_splits,
    "activity_typed_splits": activity_typed_splits,
}

for source_name, source_data in all_sources.items():
    print(f"\n=== {source_name} ===")
    hits = find_fields(source_data, KEYWORDS)
    if not hits:
        print("  (no matching fields found)")
    for field_path, example_value in hits:
        print(f"  {field_path} = {example_value!r}")

=== activity_summary ===
  metadataDTO.hasHrTimeInZones = True
  summaryDTO.averageSpeed = 3.2679998874664307
  summaryDTO.averageMovingSpeed = 3.2868925855001545
  summaryDTO.maxSpeed = 4.2270002365112305
  summaryDTO.averageHR = 169.0
  summaryDTO.maxHR = 202.0
  summaryDTO.minHR = 92.0
  summaryDTO.averageRunCadence = 175.0
  summaryDTO.maxRunCadence = 197.0
  summaryDTO.groundContactTime = 233.39999389648438
  summaryDTO.strideLength = 110.85000000000001
  summaryDTO.verticalOscillation = 8.040000152587892
  summaryDTO.verticalRatio = 7.429999828338623
  summaryDTO.maxVerticalSpeed = 1.7999997138977053
  summaryDTO.avgGradeAdjustedSpeed = 3.2739999294281006
  splitSummaries[0].averageSpeed = 0.32100000977516174
  splitSummaries[0].maxSpeed = 0.0
  splitSummaries[0].averageHR = 105.0
  splitSummaries[0].maxHR = 138.0
  splitSummaries[0].averageRunCadence = 19.65625
  splitSummaries[0].maxRunCadence = 177.0
  splitSummaries[0].strideLength = 0.0
  splitSummaries[0].avgVerticalSpeed = 0.0
  splitSummaries[0].avgGradeAdjustedSpeed = 0.0

=== activity_splits ===
  lapDTOs[0].averageSpeed = 2.815000057220459
  lapDTOs[0].averageMovingSpeed = 2.881844380403458
  lapDTOs[0].maxSpeed = 3.302999973297119
  lapDTOs[0].averageHR = 142.0
  lapDTOs[0].maxHR = 166.0
  lapDTOs[0].averageRunCadence = 170.71875
  lapDTOs[0].maxRunCadence = 180.0
  lapDTOs[0].groundContactTime = 260.29998779296875
  lapDTOs[0].strideLength = 97.92000122070313
  lapDTOs[0].verticalOscillation = 8.35
  lapDTOs[0].verticalRatio = 8.529999732971191
  lapDTOs[0].maxVerticalSpeed = 0.40000152587890625
  lapDTOs[0].avgGradeAdjustedSpeed = 2.8540000915527344

=== activity_typed_splits ===
  splits[0].averageSpeed = 0.0
  splits[0].maxSpeed = 0.0
  splits[0].averageHR = 94.0
  splits[0].maxHR = 95.0
  splits[0].averageRunCadence = 19.65625
  splits[0].maxRunCadence = 177.0
  splits[0].strideLength = 0.0
  splits[0].avgVerticalSpeed = 0.0
  splits[0].avgGradeAdjustedSpeed = 0.0
  splits[0].avgElapsedDurationVerticalSpeed = 0.02857140132359096

## Next steps

Now that we can see the real field names Garmin gives us, here's what's next:

1. **Review the output above** — check the `lapDTOs` tables in sections 4 & 5, and the
   field hits in section 6. Confirm which lap corresponds to which part of your workout
   (warmup / interval / recovery / cooldown), and which exact field names hold pace,
   cadence, GCT, and vertical oscillation for your watch model (these can vary slightly
   between Garmin devices).
2. **Check `your_data/`** — the raw JSON files saved by this notebook
   (`latest_activity_summary.json`, `latest_activity_splits.json`,
   `latest_activity_typed_splits.json`) are there for reference any time, without
   needing to re-run API calls.
3. Once we've confirmed the fields, we'll design the dashboard: a small local web app
   (Streamlit is a great beginner-friendly choice for a Python data dashboard) that
   shows your latest run with a summary card up top and a per-interval breakdown table
   below, using the exact field names we found here.